//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppADO_9_ModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class UserModelContainer : DbContext
    {
        public UserModelContainer()
            : base("name=UserModelContainer")
        {
        }

        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Department> DepartmentSet { get; set; }
    }
}

